#ifndef FLINT_VM_OP_CODE_H
#define FLINT_VM_OP_CODE_H

#define OPCODE_COUNT 161

enum OpCode {
  HALT = 0,
  PUSH_I32_0 = 1,
  PUSH_I32_1 = 2,
  PUSH_I32_1BYTE = 3,
  PUSH_I32_2BYTES = 4,
  PUSH_I64_0 = 5,
  PUSH_I64_1 = 6,
  PUSH_F32_0 = 7,
  PUSH_F32_1 = 8,
  PUSH_F64_0 = 9,
  PUSH_F64_1 = 10,
  PUSH_I32 = 11,
  PUSH_I64 = 12,
  PUSH_F32 = 13,
  PUSH_F64 = 14,
  PUSH_STRING = 15,
  PUSH_NULL = 16,
  PUSH_LOCAL_I32 = 17,
  PUSH_LOCAL_I64 = 18,
  PUSH_LOCAL_F32 = 19,
  PUSH_LOCAL_F64 = 20,
  PUSH_LOCAL_OBJECT = 21,
  POP_LOCAL_I32 = 22,
  POP_LOCAL_I64 = 23,
  POP_LOCAL_F32 = 24,
  POP_LOCAL_F64 = 25,
  POP_LOCAL_OBJECT = 26,
  PUSH_GLOBAL_I32 = 27,
  PUSH_GLOBAL_I64 = 28,
  PUSH_GLOBAL_F32 = 29,
  PUSH_GLOBAL_F64 = 30,
  PUSH_GLOBAL_OBJECT = 31,
  POP_GLOBAL_I32 = 32,
  POP_GLOBAL_I64 = 33,
  POP_GLOBAL_F32 = 34,
  POP_GLOBAL_F64 = 35,
  POP_GLOBAL_OBJECT = 36,
  PUSH_ARRAY_I32 = 37,
  PUSH_ARRAY_I64 = 38,
  PUSH_ARRAY_F32 = 39,
  PUSH_ARRAY_F64 = 40,
  PUSH_ARRAY_OBJECT = 41,
  PUSH_STRING_CHAR = 42,
  POP_ARRAY_I32 = 43,
  POP_ARRAY_I64 = 44,
  POP_ARRAY_F32 = 45,
  POP_ARRAY_F64 = 46,
  POP_ARRAY_OBJECT = 47,
  PUSH_FIELD_I32 = 48,
  PUSH_FIELD_I64 = 49,
  PUSH_FIELD_F32 = 50,
  PUSH_FIELD_F64 = 51,
  PUSH_FIELD_OBJECT = 52,
  POP_FIELD_I32 = 53,
  POP_FIELD_I64 = 54,
  POP_FIELD_F32 = 55,
  POP_FIELD_F64 = 56,
  POP_FIELD_OBJECT = 57,
  ADD_I32 = 58,
  ADD_I64 = 59,
  ADD_F32 = 60,
  ADD_F64 = 61,
  SUB_I32 = 62,
  SUB_I64 = 63,
  SUB_F32 = 64,
  SUB_F64 = 65,
  MUL_I32 = 66,
  MUL_I64 = 67,
  MUL_F32 = 68,
  MUL_F64 = 69,
  DIV_I32 = 70,
  DIV_I64 = 71,
  DIV_F32 = 72,
  DIV_F64 = 73,
  MOD_I32 = 74,
  MOD_I64 = 75,
  MOD_F32 = 76,
  MOD_F64 = 77,
  BIT_AND_I32 = 78,
  BIT_AND_I64 = 79,
  BIT_OR_I32 = 80,
  BIT_OR_I64 = 81,
  BIT_XOR_I32 = 82,
  BIT_XOR_I64 = 83,
  MINUS_I32 = 84,
  MINUS_I64 = 85,
  MINUS_F32 = 86,
  MINUS_F64 = 87,
  BIT_NOT_I32 = 88,
  BIT_NOT_I64 = 89,
  LOGICAL_NOT = 90,
  CAST_I32_TO_I64 = 91,
  CAST_I32_TO_F32 = 92,
  CAST_I32_TO_F64 = 93,
  CAST_I64_TO_I32 = 94,
  CAST_I64_TO_F32 = 95,
  CAST_I64_TO_F64 = 96,
  CAST_F32_TO_I32 = 97,
  CAST_F32_TO_I64 = 98,
  CAST_F32_TO_F64 = 99,
  CAST_F64_TO_I32 = 100,
  CAST_F64_TO_I64 = 101,
  CAST_F64_TO_F32 = 102,
  UP_CAST = 103,
  DOWN_CAST = 104,
  EQ_I32 = 105,
  EQ_I64 = 106,
  EQ_F32 = 107,
  EQ_F64 = 108,
  EQ_STRING = 109,
  NE_I32 = 110,
  NE_I64 = 111,
  NE_F32 = 112,
  NE_F64 = 113,
  NE_STRING = 114,
  GT_I32 = 115,
  GT_I64 = 116,
  GT_F32 = 117,
  GT_F64 = 118,
  GT_STRING = 119,
  LT_I32 = 120,
  LT_I64 = 121,
  LT_F32 = 122,
  LT_F64 = 123,
  LT_STRING = 124,
  GE_I32 = 125,
  GE_I64 = 126,
  GE_F32 = 127,
  GE_F64 = 128,
  GE_STRING = 129,
  LE_I32 = 130,
  LE_I64 = 131,
  LE_F32 = 132,
  LE_F64 = 133,
  LE_STRING = 134,
  POP = 135,
  DUPLICATE = 136,
  JUMP = 137,
  JUMP_IF_TRUE = 138,
  JUMP_IF_FALSE = 139,
  INVOKE_FUNCTION = 140,
  INVOKE_NATIVE_FUNCTION = 141,
  INVOKE_INTERFACE = 142,
  RETURN = 143,
  RETURN_I32 = 144,
  RETURN_I64 = 145,
  RETURN_F32 = 146,
  RETURN_F64 = 147,
  RETURN_OBJECT = 148,
  TAIL_CALL = 149,
  NEW = 150,
  NEW_ARRAY = 151,
  NEW_ARRAY_LITERAL_I32 = 152,
  NEW_ARRAY_LITERAL_I64 = 153,
  NEW_ARRAY_LITERAL_F32 = 154,
  NEW_ARRAY_LITERAL_F64 = 155,
  NEW_CLOSURE = 156,
  INVOKE_CLOSURE = 157,
  ARRAY_LENGTH = 158,
  STRING_LENGTH = 159,
  INSTANCE_OF = 160
};

static const char *opcode_info[][2] = {{"HALT", ""},
                                       {"PUSH_I32_0", ""},
                                       {"PUSH_I32_1", ""},
                                       {"PUSH_I32_1BYTE", "b"},
                                       {"PUSH_I32_2BYTES", "s"},
                                       {"PUSH_I64_0", ""},
                                       {"PUSH_I64_1", ""},
                                       {"PUSH_F32_0", ""},
                                       {"PUSH_F32_1", ""},
                                       {"PUSH_F64_0", ""},
                                       {"PUSH_F64_1", ""},
                                       {"PUSH_I32", "cp"},
                                       {"PUSH_I64", "cp"},
                                       {"PUSH_F32", "cp"},
                                       {"PUSH_F64", "cp"},
                                       {"PUSH_STRING", "cp"},
                                       {"PUSH_NULL", ""},
                                       {"PUSH_LOCAL_I32", "b"},
                                       {"PUSH_LOCAL_I64", "b"},
                                       {"PUSH_LOCAL_F32", "b"},
                                       {"PUSH_LOCAL_F64", "b"},
                                       {"PUSH_LOCAL_OBJECT", "b"},
                                       {"POP_LOCAL_I32", "b"},
                                       {"POP_LOCAL_I64", "b"},
                                       {"POP_LOCAL_F32", "b"},
                                       {"POP_LOCAL_F64", "b"},
                                       {"POP_LOCAL_OBJECT", "b"},
                                       {"PUSH_GLOBAL_I32", "b"},
                                       {"PUSH_GLOBAL_I64", "b"},
                                       {"PUSH_GLOBAL_F32", "b"},
                                       {"PUSH_GLOBAL_F64", "b"},
                                       {"PUSH_GLOBAL_OBJECT", "b"},
                                       {"POP_GLOBAL_I32", "b"},
                                       {"POP_GLOBAL_I64", "b"},
                                       {"POP_GLOBAL_F32", "b"},
                                       {"POP_GLOBAL_F64", "b"},
                                       {"POP_GLOBAL_OBJECT", "b"},
                                       {"PUSH_ARRAY_I32", ""},
                                       {"PUSH_ARRAY_I64", ""},
                                       {"PUSH_ARRAY_F32", ""},
                                       {"PUSH_ARRAY_F64", ""},
                                       {"PUSH_ARRAY_OBJECT", ""},
                                       {"PUSH_STRING_CHAR", ""},
                                       {"POP_ARRAY_I32", ""},
                                       {"POP_ARRAY_I64", ""},
                                       {"POP_ARRAY_F32", ""},
                                       {"POP_ARRAY_F64", ""},
                                       {"POP_ARRAY_OBJECT", ""},
                                       {"PUSH_FIELD_I32", "b"},
                                       {"PUSH_FIELD_I64", "b"},
                                       {"PUSH_FIELD_F32", "b"},
                                       {"PUSH_FIELD_F64", "b"},
                                       {"PUSH_FIELD_OBJECT", "b"},
                                       {"POP_FIELD_I32", "b"},
                                       {"POP_FIELD_I64", "b"},
                                       {"POP_FIELD_F32", "b"},
                                       {"POP_FIELD_F64", "b"},
                                       {"POP_FIELD_OBJECT", "b"},
                                       {"ADD_I32", ""},
                                       {"ADD_I64", ""},
                                       {"ADD_F32", ""},
                                       {"ADD_F64", ""},
                                       {"SUB_I32", ""},
                                       {"SUB_I64", ""},
                                       {"SUB_F32", ""},
                                       {"SUB_F64", ""},
                                       {"MUL_I32", ""},
                                       {"MUL_I64", ""},
                                       {"MUL_F32", ""},
                                       {"MUL_F64", ""},
                                       {"DIV_I32", ""},
                                       {"DIV_I64", ""},
                                       {"DIV_F32", ""},
                                       {"DIV_F64", ""},
                                       {"MOD_I32", ""},
                                       {"MOD_I64", ""},
                                       {"MOD_F32", ""},
                                       {"MOD_F64", ""},
                                       {"BIT_AND_I32", ""},
                                       {"BIT_AND_I64", ""},
                                       {"BIT_OR_I32", ""},
                                       {"BIT_OR_I64", ""},
                                       {"BIT_XOR_I32", ""},
                                       {"BIT_XOR_I64", ""},
                                       {"MINUS_I32", ""},
                                       {"MINUS_I64", ""},
                                       {"MINUS_F32", ""},
                                       {"MINUS_F64", ""},
                                       {"BIT_NOT_I32", ""},
                                       {"BIT_NOT_I64", ""},
                                       {"LOGICAL_NOT", ""},
                                       {"CAST_I32_TO_I64", ""},
                                       {"CAST_I32_TO_F32", ""},
                                       {"CAST_I32_TO_F64", ""},
                                       {"CAST_I64_TO_I32", ""},
                                       {"CAST_I64_TO_F32", ""},
                                       {"CAST_I64_TO_F64", ""},
                                       {"CAST_F32_TO_I32", ""},
                                       {"CAST_F32_TO_I64", ""},
                                       {"CAST_F32_TO_F64", ""},
                                       {"CAST_F64_TO_I32", ""},
                                       {"CAST_F64_TO_I64", ""},
                                       {"CAST_F64_TO_F32", ""},
                                       {"UP_CAST", "b"},
                                       {"DOWN_CAST", "b"},
                                       {"EQ_I32", ""},
                                       {"EQ_I64", ""},
                                       {"EQ_F32", ""},
                                       {"EQ_F64", ""},
                                       {"EQ_STRING", ""},
                                       {"NE_I32", ""},
                                       {"NE_I64", ""},
                                       {"NE_F32", ""},
                                       {"NE_F64", ""},
                                       {"NE_STRING", ""},
                                       {"GT_I32", ""},
                                       {"GT_I64", ""},
                                       {"GT_F32", ""},
                                       {"GT_F64", ""},
                                       {"GT_STRING", ""},
                                       {"LT_I32", ""},
                                       {"LT_I64", ""},
                                       {"LT_F32", ""},
                                       {"LT_F64", ""},
                                       {"LT_STRING", ""},
                                       {"GE_I32", ""},
                                       {"GE_I64", ""},
                                       {"GE_F32", ""},
                                       {"GE_F64", ""},
                                       {"GE_STRING", ""},
                                       {"LE_I32", ""},
                                       {"LE_I64", ""},
                                       {"LE_F32", ""},
                                       {"LE_F64", ""},
                                       {"LE_STRING", ""},
                                       {"POP", ""},
                                       {"DUPLICATE", ""},
                                       {"JUMP", "s"},
                                       {"JUMP_IF_TRUE", "s"},
                                       {"JUMP_IF_FALSE", "s"},
                                       {"INVOKE_FUNCTION", "cp"},
                                       {"INVOKE_NATIVE_FUNCTION", "cp"},
                                       {"INVOKE_INTERFACE", "cp"},
                                       {"RETURN", ""},
                                       {"RETURN_I32", ""},
                                       {"RETURN_I64", ""},
                                       {"RETURN_F32", ""},
                                       {"RETURN_F64", ""},
                                       {"RETURN_OBJECT", ""},
                                       {"TAIL_CALL", "b"},
                                       {"NEW", "cp"},
                                       {"NEW_ARRAY", "b"},
                                       {"NEW_ARRAY_LITERAL_I32", "u"},
                                       {"NEW_ARRAY_LITERAL_I64", "u"},
                                       {"NEW_ARRAY_LITERAL_F32", "u"},
                                       {"NEW_ARRAY_LITERAL_F64", "u"},
                                       {"NEW_CLOSURE", "cp"},
                                       {"INVOKE_CLOSURE", ""},
                                       {"ARRAY_LENGTH", ""},
                                       {"STRING_LENGTH", ""},
                                       {"INSTANCE_OF", "b"}};

#endif /* FLINT_VM_OP_CODE_H */
