#ifndef FLINT_VM_OP_CODE_H
#define FLINT_VM_OP_CODE_H

enum OpCode {
  PUSH_I32_0 = 0,
  PUSH_I32_1 = 1,
  PUSH_I32_1BYTE = 2,
  PUSH_I32_2BYTE = 3,
  PUSH_I64_0 = 4,
  PUSH_I64_1 = 5,
  PUSH_F64_0 = 6,
  PUSH_F64_1 = 7,
  PUSH_I32 = 8,
  PUSH_I64 = 9,
  PUSH_F32 = 10,
  PUSH_F64 = 11,
  PUSH_STRING = 12,
  PUSH_NULL = 13,
  PUSH_LOCAL_I32 = 14,
  PUSH_LOCAL_I64 = 15,
  PUSH_LOCAL_F32 = 16,
  PUSH_LOCAL_F64 = 17,
  PUSH_LOCAL_OBJECT = 18,
  POP_LOCAL_I32 = 19,
  POP_LOCAL_I64 = 20,
  POP_LOCAL_F32 = 21,
  POP_LOCAL_F64 = 22,
  POP_LOCAL_OBJECT = 23,
  PUSH_STATIC_I32 = 24,
  PUSH_STATIC_I64 = 25,
  PUSH_STATIC_F32 = 26,
  PUSH_STATIC_F64 = 27,
  PUSH_STATIC_OBJECT = 28,
  POP_STATIC_I32 = 29,
  POP_STATIC_I64 = 30,
  POP_STATIC_F32 = 31,
  POP_STATIC_F64 = 32,
  POP_STATIC_OBJECT = 33,
  PUSH_ARRAY_I32 = 34,
  PUSH_ARRAY_I64 = 35,
  PUSH_ARRAY_F32 = 36,
  PUSH_ARRAY_F64 = 37,
  PUSH_ARRAY_OBJECT = 38,
  POP_ARRAY_I32 = 39,
  POP_ARRAY_I64 = 40,
  POP_ARRAY_F32 = 41,
  POP_ARRAY_F64 = 42,
  POP_ARRAY_OBJECT = 43,
  PUSH_FIELD_I32 = 44,
  PUSH_FIELD_I64 = 45,
  PUSH_FIELD_F32 = 46,
  PUSH_FIELD_F64 = 47,
  PUSH_FIELD_OBJECT = 48,
  POP_FIELD_I32 = 49,
  POP_FIELD_I64 = 50,
  POP_FIELD_F32 = 51,
  POP_FIELD_F64 = 52,
  POP_FIELD_OBJECT = 53,
  ADD_I32 = 54,
  ADD_I64 = 55,
  ADD_F32 = 56,
  ADD_F64 = 57,
  ADD_DYNAMIC = 58,
  SUB_I32 = 59,
  SUB_I64 = 60,
  SUB_F32 = 61,
  SUB_F64 = 62,
  SUB_DYNAMIC = 63,
  MUL_I32 = 64,
  MUL_I64 = 65,
  MUL_F32 = 66,
  MUL_F64 = 67,
  MUL_DYNAMIC = 68,
  DIV_I32 = 69,
  DIV_I64 = 70,
  DIV_F32 = 71,
  DIV_F64 = 72,
  DIV_DYNAMIC = 73,
  MOD_I32 = 74,
  MOD_I64 = 75,
  MOD_F32 = 76,
  MOD_F64 = 77,
  MOD_DYNAMIC = 78,
  BIT_AND_I32 = 79,
  BIT_AND_I64 = 80,
  BIT_AND_DYNAMIC = 81,
  BIT_OR_I32 = 82,
  BIT_OR_I64 = 83,
  BIT_OR_DYNAMIC = 84,
  BIT_XOR_I32 = 85,
  BIT_XOR_I64 = 86,
  BIT_XOR_DYNAMIC = 87,
  MINUS_I32 = 88,
  MINUS_I64 = 89,
  MINUS_F32 = 90,
  MINUS_F64 = 91,
  MINUS_DYNAMIC = 92,
  BIT_NOT_I32 = 93,
  BIT_NOT_I64 = 94,
  BIT_NOT_DYNAMIC = 95,
  CAST_I32_TO_I64 = 96,
  CAST_I32_TO_F32 = 97,
  CAST_I32_TO_F64 = 98,
  CAST_I64_TO_I32 = 99,
  CAST_I64_TO_F32 = 100,
  CAST_I64_TO_F64 = 101,
  CAST_F32_TO_I32 = 102,
  CAST_F32_TO_I64 = 103,
  CAST_F32_TO_F64 = 104,
  CAST_F64_TO_I32 = 105,
  CAST_F64_TO_I64 = 106,
  CAST_F64_TO_F32 = 107,
  UP_CAST = 108,
  DOWN_CAST = 109,
  EQ_I32 = 110,
  EQ_I64 = 111,
  EQ_F32 = 112,
  EQ_F64 = 113,
  EQ_DYNAMIC = 114,
  NE_I32 = 115,
  NE_I64 = 116,
  NE_F32 = 117,
  NE_F64 = 118,
  NE_DYNAMIC = 119,
  GT_I32 = 120,
  GT_I64 = 121,
  GT_F32 = 122,
  GT_F64 = 123,
  GT_DYNAMIC = 124,
  LT_I32 = 125,
  LT_I64 = 126,
  LT_F32 = 127,
  LT_F64 = 128,
  LT_DYNAMIC = 129,
  GE_I32 = 130,
  GE_I64 = 131,
  GE_F32 = 132,
  GE_F64 = 133,
  GE_DYNAMIC = 134,
  LE_I32 = 135,
  LE_I64 = 136,
  LE_F32 = 137,
  LE_F64 = 138,
  LE_DYNAMIC = 139,
  POP = 140,
  DUPLICATE = 141,
  DUPLICATE_OFFSET = 142,
  JUMP = 143,
  JUMP_IF_TRUE = 144,
  JUMP_IF_FALSE = 145,
  PUSH_FUNCTION = 146,
  PUSH_METHOD = 147,
  INVOKE = 148,
  RETURN_I32 = 149,
  RETURN_I64 = 150,
  RETURN_F32 = 151,
  RETURN_F64 = 152,
  RETURN_OBJECT = 153,
  NEW = 154,
  NEW_ARRAY = 155,
  NEW_ARRAY_LITERAL_I32 = 156,
  NEW_ARRAY_LITERAL_I64 = 157,
  NEW_ARRAY_LITERAL_F32 = 158,
  NEW_ARRAY_LITERAL_F64 = 159,
  NEW_ARRAY_LITERAL_DYNAMIC = 160,
  ARRAY_LENGTH = 161,
  SUPER = 162,
  INSTANCE_OF = 163,
  THROW = 164,
  RETHROW = 165,
  GO_FINALLY = 166,
  FINALLY_END = 167
};

const char *opcode_info[][2] = {{"PUSH_I32_0", ""},
                                {"PUSH_I32_1", ""},
                                {"PUSH_I32_1BYTE", "b"},
                                {"PUSH_I32_2BYTE", "u"},
                                {"PUSH_I64_0", ""},
                                {"PUSH_I64_1", ""},
                                {"PUSH_F64_0", ""},
                                {"PUSH_F64_1", ""},
                                {"PUSH_I32", "p"},
                                {"PUSH_I64", "p"},
                                {"PUSH_F32", "p"},
                                {"PUSH_F64", "p"},
                                {"PUSH_STRING", "p"},
                                {"PUSH_NULL", ""},
                                {"PUSH_LOCAL_I32", "u"},
                                {"PUSH_LOCAL_I64", "u"},
                                {"PUSH_LOCAL_F32", "u"},
                                {"PUSH_LOCAL_F64", "u"},
                                {"PUSH_LOCAL_OBJECT", "u"},
                                {"POP_LOCAL_I32", "u"},
                                {"POP_LOCAL_I64", "u"},
                                {"POP_LOCAL_F32", "u"},
                                {"POP_LOCAL_F64", "u"},
                                {"POP_LOCAL_OBJECT", "u"},
                                {"PUSH_STATIC_I32", "uu"},
                                {"PUSH_STATIC_I64", "uu"},
                                {"PUSH_STATIC_F32", "uu"},
                                {"PUSH_STATIC_F64", "uu"},
                                {"PUSH_STATIC_OBJECT", "uu"},
                                {"POP_STATIC_I32", "uu"},
                                {"POP_STATIC_I64", "uu"},
                                {"POP_STATIC_F32", "uu"},
                                {"POP_STATIC_F64", "uu"},
                                {"POP_STATIC_OBJECT", "uu"},
                                {"PUSH_ARRAY_I32", ""},
                                {"PUSH_ARRAY_I64", ""},
                                {"PUSH_ARRAY_F32", ""},
                                {"PUSH_ARRAY_F64", ""},
                                {"PUSH_ARRAY_OBJECT", ""},
                                {"POP_ARRAY_I32", ""},
                                {"POP_ARRAY_I64", ""},
                                {"POP_ARRAY_F32", ""},
                                {"POP_ARRAY_F64", ""},
                                {"POP_ARRAY_OBJECT", ""},
                                {"PUSH_FIELD_I32", "u"},
                                {"PUSH_FIELD_I64", "u"},
                                {"PUSH_FIELD_F32", "u"},
                                {"PUSH_FIELD_F64", "u"},
                                {"PUSH_FIELD_OBJECT", "u"},
                                {"POP_FIELD_I32", "u"},
                                {"POP_FIELD_I64", "u"},
                                {"POP_FIELD_F32", "u"},
                                {"POP_FIELD_F64", "u"},
                                {"POP_FIELD_OBJECT", "u"},
                                {"ADD_I32", ""},
                                {"ADD_I64", ""},
                                {"ADD_F32", ""},
                                {"ADD_F64", ""},
                                {"ADD_DYNAMIC", ""},
                                {"SUB_I32", ""},
                                {"SUB_I64", ""},
                                {"SUB_F32", ""},
                                {"SUB_F64", ""},
                                {"SUB_DYNAMIC", ""},
                                {"MUL_I32", ""},
                                {"MUL_I64", ""},
                                {"MUL_F32", ""},
                                {"MUL_F64", ""},
                                {"MUL_DYNAMIC", ""},
                                {"DIV_I32", ""},
                                {"DIV_I64", ""},
                                {"DIV_F32", ""},
                                {"DIV_F64", ""},
                                {"DIV_DYNAMIC", ""},
                                {"MOD_I32", ""},
                                {"MOD_I64", ""},
                                {"MOD_F32", ""},
                                {"MOD_F64", ""},
                                {"MOD_DYNAMIC", ""},
                                {"BIT_AND_I32", ""},
                                {"BIT_AND_I64", ""},
                                {"BIT_AND_DYNAMIC", ""},
                                {"BIT_OR_I32", ""},
                                {"BIT_OR_I64", ""},
                                {"BIT_OR_DYNAMIC", ""},
                                {"BIT_XOR_I32", ""},
                                {"BIT_XOR_I64", ""},
                                {"BIT_XOR_DYNAMIC", ""},
                                {"MINUS_I32", ""},
                                {"MINUS_I64", ""},
                                {"MINUS_F32", ""},
                                {"MINUS_F64", ""},
                                {"MINUS_DYNAMIC", ""},
                                {"BIT_NOT_I32", ""},
                                {"BIT_NOT_I64", ""},
                                {"BIT_NOT_DYNAMIC", ""},
                                {"CAST_I32_TO_I64", ""},
                                {"CAST_I32_TO_F32", ""},
                                {"CAST_I32_TO_F64", ""},
                                {"CAST_I64_TO_I32", ""},
                                {"CAST_I64_TO_F32", ""},
                                {"CAST_I64_TO_F64", ""},
                                {"CAST_F32_TO_I32", ""},
                                {"CAST_F32_TO_I64", ""},
                                {"CAST_F32_TO_F64", ""},
                                {"CAST_F64_TO_I32", ""},
                                {"CAST_F64_TO_I64", ""},
                                {"CAST_F64_TO_F32", ""},
                                {"UP_CAST", "u"},
                                {"DOWN_CAST", "u"},
                                {"EQ_I32", ""},
                                {"EQ_I64", ""},
                                {"EQ_F32", ""},
                                {"EQ_F64", ""},
                                {"EQ_DYNAMIC", ""},
                                {"NE_I32", ""},
                                {"NE_I64", ""},
                                {"NE_F32", ""},
                                {"NE_F64", ""},
                                {"NE_DYNAMIC", ""},
                                {"GT_I32", ""},
                                {"GT_I64", ""},
                                {"GT_F32", ""},
                                {"GT_F64", ""},
                                {"GT_DYNAMIC", ""},
                                {"LT_I32", ""},
                                {"LT_I64", ""},
                                {"LT_F32", ""},
                                {"LT_F64", ""},
                                {"LT_DYNAMIC", ""},
                                {"GE_I32", ""},
                                {"GE_I64", ""},
                                {"GE_F32", ""},
                                {"GE_F64", ""},
                                {"GE_DYNAMIC", ""},
                                {"LE_I32", ""},
                                {"LE_I64", ""},
                                {"LE_F32", ""},
                                {"LE_F64", ""},
                                {"LE_DYNAMIC", ""},
                                {"POP", ""},
                                {"DUPLICATE", ""},
                                {"DUPLICATE_OFFSET", "u"},
                                {"JUMP", "u"},
                                {"JUMP_IF_TRUE", "u"},
                                {"JUMP_IF_FALSE", "u"},
                                {"PUSH_FUNCTION", "uu"},
                                {"PUSH_METHOD", "uu"},
                                {"INVOKE", ""},
                                {"RETURN_I32", ""},
                                {"RETURN_I64", ""},
                                {"RETURN_F32", ""},
                                {"RETURN_F64", ""},
                                {"RETURN_OBJECT", ""},
                                {"NEW", "u"},
                                {"NEW_ARRAY", "bu"},
                                {"NEW_ARRAY_LITERAL_I32", "u"},
                                {"NEW_ARRAY_LITERAL_I64", "u"},
                                {"NEW_ARRAY_LITERAL_F32", "u"},
                                {"NEW_ARRAY_LITERAL_F64", "u"},
                                {"NEW_ARRAY_LITERAL_DYNAMIC", "u"},
                                {"ARRAY_LENGTH", ""},
                                {"SUPER", ""},
                                {"INSTANCE_OF", "u"},
                                {"THROW", ""},
                                {"RETHROW", ""},
                                {"GO_FINALLY", "u"},
                                {"FINALLY_END", ""}};

#endif